name: CI

on:
    push:
        branches: [ develop ]
    pull_request:
        branches: [ develop ]

jobs:
    test:
        name: Test
        runs-on: ubuntu-latest
        steps:
            -   name: Set up environment
                uses: actions/setup-go@v3
                with:
                    go-version: '1.21'
            -   name: Checkout repository
                uses: actions/checkout@v3
            -   name: Run tests
                run: go test -v -cover -count=100 .
    lint:
        name: Lint
        runs-on: ubuntu-latest
        steps:
            -   name: Set up environment
                uses: actions/setup-go@v3
                with:
                    go-version: '1.21'
            -   name: Checkout repository
                uses: actions/checkout@v3
            -   name: Run golangci-linter
                uses: golangci/golangci-lint-action@v3
                with:
                    version: v1.54